rtp:
  min:
    x: 0
    y: 70
    z: 1000
  max:
    x: 1000
    y: 150
    z: 2000
  maxattemps: 10
  world: "world"
  cooldown: 10  #(300 = 5 minutes)
  delay: 60      # (3 seconds)
  maxattempts: 50
  effects:
    particles: true
    sounds: true
